### ISSUE TITLE
启动时每次都提示上次崩溃了

### ISSUE THREAD

**Issue by Howard20181** [lz233/OneText_For_Android#16]
抱歉，本应用在上次崩溃了。如果你愿意，请复制日志并发送邮件到 lz23333333@gmail.com。

AppNamespace: `com.lz233.onetext`

AppVersion: `1.83-ぬ`

AppBuild: `20201205`

OemName: `Xiaomi`

Model: `MI 9`

OsName: `Android`

OsVersion: `11`

OsApiLevel: `30`

OsBuild: `RKQ1.200826.002`

SdkVersion: `3.2.2`

Locale: `zh_CN`

ScreenSize: `1080x2221`

ThreadName: `main`

StackTrace:
```bash
java.lang.RuntimeException: Unable to create service com.lz233.onetext.service.ExternalControlService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4308)
	at android.app.ActivityThread.access$1700(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2001)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.app.PendingIntent.getActivity(PendingIntent.java:352)
	at android.app.PendingIntent.getActivity(PendingIntent.java:319)
	at com.lz233.onetext.service.ExternalControlService.<init>(Unknown Source:22)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at androidx.core.app.CoreComponentFactory.instantiateService(Unknown Source:0)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4287)
	... 8 more
```

**Comment by lz233** [comment]
@Howard20181 没做完 Android 11 的设备控制。
